version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
       - .:/sessions
  redis:
    image: "redis:alpine"

volumes:
    sessions:
        driver: local